version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - s-weigand
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '>= 14'
          - '< 15'
